{-cp -b -dRUSSIAN -dUSESTANDARDBITMAPS}
{$DEFINE RUSSIAN}
{$DEFINE USESTANDARDBITMAPS}
{*******************************************************}
{                                                       }
{       Express Graphics Build Program                  }
{                                                       }
{  Version 1.00 (based on TV version 2), Revision 013   }
{                                                       }
{    Copyright (c) 1994 Berezin, Oleinick and Shimon    }
{  Portions Copyright (c) 1992 by Borland International }
{                                                       }
{*******************************************************}

unit Build;

interface

uses
  Strings,
  Objects,
  Drivers,
  Memory,
  Views,
  Menus,
  Dialogs,
  StdDlg,
  MsgBox,
  TextView,
  Colorsel,
  Editors,
  App,
  Validate,
  Outline,
  Gadgets,
  EgScrSaver,
  WallPapers,
  Fields,
  Mono,
  EGVG,
  SVGA256,
  SVGA32K,
  SVGA64K,
  SVGA16M,
  Palettes,
  GDI,
  EgDPMI,
  EgInline,
  EgString,
  EgDate,
  EgPrint,
  FntLib,
  Notebook,
  MMonolog,
  Labels,
  Afterdrk,
  Flick,
  Streams,
  XMM,
  WavePlay,
  Blaster,
  Speaker,
  TrueType,
  Image,
  Printers,
  CDialogs;

implementation
begin
end.
